FROM quay.io/fedora/fedora:37

ARG USER_NAME

RUN dnf -y update && \
    dnf -y reinstall shadow-utils && \
    dnf -y install dotnet-sdk-7.0 podman \
                   # podman dependencies
                   fuse-overlayfs --exclude container-selinux \
                   xterm && \
    dnf clean all
RUN useradd -u 1000 ${USER_NAME} && echo ${USER_NAME}:10000:5000 > /etc/subuid && echo ${USER_NAME}:10000:5000 > /etc/subgid

# Disable telemetry
RUN mkdir -p /home/${USER_NAME}/.local/share/containers/${USER_NAME}/configuration && \
    echo '{"telemetry.enabled": false, "telemetry.check": true}' > /home/${USER_NAME}/.local/share/containers/${USER_NAME}/configuration/settings.json

# initialize conf files

ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/containers.conf /etc/containers/containers.conf
ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/podman-containers.conf /home/${USER_NAME}/.config/containers/containers.conf

# set permissions
RUN chown ${USER_NAME}:${USER_NAME} -R /home/${USER_NAME} && chmod 644 /etc/containers/containers.conf && \
    mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; touch /var/lib/shared/vfs-layers/layers.lock && \
    mkdir -p /run/user/1000 && chown ${USER_NAME}:${USER_NAME} /run/user/1000
COPY ["./entrypoint.sh", "/usr/local/${USER_NAME}/"]

ENV _CONTAINERS_USERNS_CONFIGURED=""

# socket path for podman
ENV XDG_RUNTIME_DIR=/run/user/1000

ENTRYPOINT [ "/usr/local/${USER_NAME}/entrypoint.sh" ]
USER ${USER_NAME}
CMD ["sleep", "infinity"]