create table if not exists outbox_state
(
    id        uuid default gen_random_uuid() not null primary key,
    expire_at timestamp                      not null
);

create table if not exists outbox_message
(
    id          bigint generated by default as identity,
    destination text,
    key         bytea,
    value       bytea     not null,
    created_at  timestamp not null
);